In [65]:
import numpy as np


In [66]:
array1d = np.array([1,2,3,4,5,6])
array2d = np.array([[1,2,3],[4,5,6]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [67]:
array1d

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [68]:
array1d[1:]

array([2, 3, 4, 5, 6])

array([2, 3, 4, 5, 6])

array([2, 3, 4, 5, 6])

In [69]:
array1d[3:5]

array([4, 5])

array([4, 5])

array([4, 5])

In [70]:
array1d[-3:-1]

array([4, 5])

array([4, 5])

array([4, 5])

In [71]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
array2d[1,1:]

array([5, 6])

array([5, 6])

array([5, 6])

In [73]:
array2d[-2:-3:-1]

array([[1, 2, 3]])

array([[1, 2, 3]])

array([[1, 2, 3]])

In [74]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
array3d[0,1:1]

array([], shape=(0, 3), dtype=int32)

array([], shape=(0, 3), dtype=int32)

array([], shape=(0, 3), dtype=int32)