In [12]:
import numpy as np


In [13]:
array1d = np.array([1,2,3,4,5,6])
array2d = np.array([[1,2,3],[4,5,6]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [14]:
array1d

array([1, 2, 3, 4, 5, 6])

In [15]:
array1d[1:]

array([2, 3, 4, 5, 6])

In [16]:
array1d[3:5]

array([4, 5])

In [17]:
array1d[-3:-1]

array([4, 5])

In [18]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array2d[1,1:]

array([5, 6])

In [20]:
array2d[-2:-3:-1]

array([[1, 2, 3]])

In [21]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
array3d[0,1:1]

array([], shape=(0, 3), dtype=int32)