In [1]:
import numpy as np


In [2]:
array1d = np.array([1,2,3,4,5,6])
array2d = np.array([[1,2,3],[4,5,6]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [3]:
array1d

array([1, 2, 3, 4, 5, 6])

In [4]:
array1d[1:]

array([2, 3, 4, 5, 6])

In [5]:
array1d[3:5]

array([4, 5])

In [6]:
array1d[-3:-1]

array([4, 5])

In [7]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array2d[1,1:]

array([5, 6])

In [9]:
array2d[-2:-3:-1]

array([[1, 2, 3]])

In [10]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
array3d[0,1:1]

array([], shape=(0, 3), dtype=int32)